export interface Country {
  code: string // ISO 3166-1 alpha-2，小写，直接喂给 Nominatim 的 countrycodes 参数
  nameZh: string
  nameEn: string
}

// 常见旅行目的地国家/地区，按中文名搜索用。没有做到 ISO 全部 195+ 个是因为
// 家庭旅游APP用不到的冷门地区收益很低，这份列表覆盖亚洲全部+欧美主要国家+
// 大洋洲/中东/非洲热门目的地，足够用；真遇到列表里没有的地方，行程可以不设国家
// （地点搜索就不过滤，退回原来的全球搜索）。
export const COUNTRIES: Country[] = [
  { code: 'cn', nameZh: '中国', nameEn: 'China' },
  { code: 'hk', nameZh: '中国香港', nameEn: 'Hong Kong' },
  { code: 'mo', nameZh: '中国澳门', nameEn: 'Macau' },
  { code: 'tw', nameZh: '中国台湾', nameEn: 'Taiwan' },
  { code: 'jp', nameZh: '日本', nameEn: 'Japan' },
  { code: 'kr', nameZh: '韩国', nameEn: 'South Korea' },
  { code: 'kp', nameZh: '朝鲜', nameEn: 'North Korea' },
  { code: 'my', nameZh: '马来西亚', nameEn: 'Malaysia' },
  { code: 'sg', nameZh: '新加坡', nameEn: 'Singapore' },
  { code: 'th', nameZh: '泰国', nameEn: 'Thailand' },
  { code: 'vn', nameZh: '越南', nameEn: 'Vietnam' },
  { code: 'kh', nameZh: '柬埔寨', nameEn: 'Cambodia' },
  { code: 'la', nameZh: '老挝', nameEn: 'Laos' },
  { code: 'mm', nameZh: '缅甸', nameEn: 'Myanmar' },
  { code: 'ph', nameZh: '菲律宾', nameEn: 'Philippines' },
  { code: 'id', nameZh: '印度尼西亚', nameEn: 'Indonesia' },
  { code: 'bn', nameZh: '布鲁乃', nameEn: 'Brunei' },
  { code: 'in', nameZh: '印度', nameEn: 'India' },
  { code: 'pk', nameZh: '巴基斯坦', nameEn: 'Pakistan' },
  { code: 'bd', nameZh: '孟加拉国', nameEn: 'Bangladesh' },
  { code: 'lk', nameZh: '斯里兰卡', nameEn: 'Sri Lanka' },
  { code: 'np', nameZh: '尼泊尔', nameEn: 'Nepal' },
  { code: 'bt', nameZh: '不丹', nameEn: 'Bhutan' },
  { code: 'mv', nameZh: '马尔代夫', nameEn: 'Maldives' },
  { code: 'mn', nameZh: '蒙古', nameEn: 'Mongolia' },
  { code: 'kz', nameZh: '哈萨克斯坦', nameEn: 'Kazakhstan' },
  { code: 'uz', nameZh: '乌兹别克斯坦', nameEn: 'Uzbekistan' },
  { code: 'kg', nameZh: '吉尔吉斯斯坦', nameEn: 'Kyrgyzstan' },
  { code: 'tj', nameZh: '塔吉克斯坦', nameEn: 'Tajikistan' },
  { code: 'tm', nameZh: '土库曼斯坦', nameEn: 'Turkmenistan' },
  { code: 'af', nameZh: '阿富汗', nameEn: 'Afghanistan' },
  { code: 'ae', nameZh: '阿联酋', nameEn: 'United Arab Emirates' },
  { code: 'sa', nameZh: '沙特阿拉伯', nameEn: 'Saudi Arabia' },
  { code: 'qa', nameZh: '卡塔尔', nameEn: 'Qatar' },
  { code: 'kw', nameZh: '科威特', nameEn: 'Kuwait' },
  { code: 'bh', nameZh: '巴林', nameEn: 'Bahrain' },
  { code: 'om', nameZh: '阿曼', nameEn: 'Oman' },
  { code: 'jo', nameZh: '约旦', nameEn: 'Jordan' },
  { code: 'il', nameZh: '以色列', nameEn: 'Israel' },
  { code: 'ps', nameZh: '巴勒斯坦', nameEn: 'Palestine' },
  { code: 'lb', nameZh: '黎巴嫩', nameEn: 'Lebanon' },
  { code: 'tr', nameZh: '土耳其', nameEn: 'Turkey' },
  { code: 'ir', nameZh: '伊朗', nameEn: 'Iran' },
  { code: 'iq', nameZh: '伊拉克', nameEn: 'Iraq' },
  { code: 'ge', nameZh: '格鲁吉亚', nameEn: 'Georgia' },
  { code: 'am', nameZh: '亚美尼亚', nameEn: 'Armenia' },
  { code: 'az', nameZh: '阿塞拜疆', nameEn: 'Azerbaijan' },
  { code: 'gb', nameZh: '英国', nameEn: 'United Kingdom' },
  { code: 'ie', nameZh: '爱尔兰', nameEn: 'Ireland' },
  { code: 'fr', nameZh: '法国', nameEn: 'France' },
  { code: 'de', nameZh: '德国', nameEn: 'Germany' },
  { code: 'nl', nameZh: '荷兰', nameEn: 'Netherlands' },
  { code: 'be', nameZh: '比利时', nameEn: 'Belgium' },
  { code: 'lu', nameZh: '卢森堡', nameEn: 'Luxembourg' },
  { code: 'ch', nameZh: '瑞士', nameEn: 'Switzerland' },
  { code: 'at', nameZh: '奥地利', nameEn: 'Austria' },
  { code: 'it', nameZh: '意大利', nameEn: 'Italy' },
  { code: 'es', nameZh: '西班牙', nameEn: 'Spain' },
  { code: 'pt', nameZh: '葡萄牙', nameEn: 'Portugal' },
  { code: 'gr', nameZh: '希腊', nameEn: 'Greece' },
  { code: 'cy', nameZh: '塞浦路斯', nameEn: 'Cyprus' },
  { code: 'mt', nameZh: '马耳他', nameEn: 'Malta' },
  { code: 'dk', nameZh: '丹麦', nameEn: 'Denmark' },
  { code: 'no', nameZh: '挪威', nameEn: 'Norway' },
  { code: 'se', nameZh: '瑞典', nameEn: 'Sweden' },
  { code: 'fi', nameZh: '芬兰', nameEn: 'Finland' },
  { code: 'is', nameZh: '冰岛', nameEn: 'Iceland' },
  { code: 'pl', nameZh: '波兰', nameEn: 'Poland' },
  { code: 'cz', nameZh: '捷克', nameEn: 'Czech Republic' },
  { code: 'sk', nameZh: '斯洛伐克', nameEn: 'Slovakia' },
  { code: 'hu', nameZh: '匈牙利', nameEn: 'Hungary' },
  { code: 'ro', nameZh: '罗马尼亚', nameEn: 'Romania' },
  { code: 'bg', nameZh: '保加利亚', nameEn: 'Bulgaria' },
  { code: 'hr', nameZh: '克罗地亚', nameEn: 'Croatia' },
  { code: 'si', nameZh: '斯洛文尼亚', nameEn: 'Slovenia' },
  { code: 'rs', nameZh: '塞尔维亚', nameEn: 'Serbia' },
  { code: 'ba', nameZh: '波黑', nameEn: 'Bosnia and Herzegovina' },
  { code: 'me', nameZh: '黑山', nameEn: 'Montenegro' },
  { code: 'mk', nameZh: '北马其顿', nameEn: 'North Macedonia' },
  { code: 'al', nameZh: '阿尔巴尼亚', nameEn: 'Albania' },
  { code: 'ua', nameZh: '乌克兰', nameEn: 'Ukraine' },
  { code: 'by', nameZh: '白俄罗斯', nameEn: 'Belarus' },
  { code: 'md', nameZh: '摩尔多瓦', nameEn: 'Moldova' },
  { code: 'ru', nameZh: '俄罗斯', nameEn: 'Russia' },
  { code: 'ee', nameZh: '爱沙尼亚', nameEn: 'Estonia' },
  { code: 'lv', nameZh: '拉脱维亚', nameEn: 'Latvia' },
  { code: 'lt', nameZh: '立陶宛', nameEn: 'Lithuania' },
  { code: 'us', nameZh: '美国', nameEn: 'United States' },
  { code: 'ca', nameZh: '加拿大', nameEn: 'Canada' },
  { code: 'mx', nameZh: '墨西哥', nameEn: 'Mexico' },
  { code: 'cu', nameZh: '古巴', nameEn: 'Cuba' },
  { code: 'jm', nameZh: '牙买加', nameEn: 'Jamaica' },
  { code: 'do', nameZh: '多米尼加', nameEn: 'Dominican Republic' },
  { code: 'bs', nameZh: '巴哈马', nameEn: 'Bahamas' },
  { code: 'pa', nameZh: '巴拿马', nameEn: 'Panama' },
  { code: 'cr', nameZh: '哥斯达黎加', nameEn: 'Costa Rica' },
  { code: 'gt', nameZh: '危地马拉', nameEn: 'Guatemala' },
  { code: 'br', nameZh: '巴西', nameEn: 'Brazil' },
  { code: 'ar', nameZh: '阿根廷', nameEn: 'Argentina' },
  { code: 'cl', nameZh: '智利', nameEn: 'Chile' },
  { code: 'pe', nameZh: '秘鲁', nameEn: 'Peru' },
  { code: 'co', nameZh: '哥伦比亚', nameEn: 'Colombia' },
  { code: 've', nameZh: '委内瑞拉', nameEn: 'Venezuela' },
  { code: 'ec', nameZh: '厄瓜多尔', nameEn: 'Ecuador' },
  { code: 'bo', nameZh: '玻利维亚', nameEn: 'Bolivia' },
  { code: 'uy', nameZh: '乌拉圭', nameEn: 'Uruguay' },
  { code: 'py', nameZh: '巴拉圭', nameEn: 'Paraguay' },
  { code: 'au', nameZh: '澳大利亚', nameEn: 'Australia' },
  { code: 'nz', nameZh: '新西兰', nameEn: 'New Zealand' },
  { code: 'fj', nameZh: '斐济', nameEn: 'Fiji' },
  { code: 'pg', nameZh: '巴布亚新几内亚', nameEn: 'Papua New Guinea' },
  { code: 'eg', nameZh: '埃及', nameEn: 'Egypt' },
  { code: 'ma', nameZh: '摩洛哥', nameEn: 'Morocco' },
  { code: 'tn', nameZh: '突尼斯', nameEn: 'Tunisia' },
  { code: 'za', nameZh: '南非', nameEn: 'South Africa' },
  { code: 'ke', nameZh: '肯尼亚', nameEn: 'Kenya' },
  { code: 'tz', nameZh: '坦桑尼亚', nameEn: 'Tanzania' },
  { code: 'et', nameZh: '埃塞俄比亚', nameEn: 'Ethiopia' },
  { code: 'ng', nameZh: '尼日利亚', nameEn: 'Nigeria' },
  { code: 'gh', nameZh: '加纳', nameEn: 'Ghana' },
  { code: 'mu', nameZh: '毛里求斯', nameEn: 'Mauritius' },
  { code: 'sc', nameZh: '塞舌尔', nameEn: 'Seychelles' },
]

export function searchCountries(query: string): Country[] {
  const q = query.trim().toLowerCase()
  if (!q) return []
  return COUNTRIES.filter((c) => c.nameZh.includes(query.trim()) || c.nameEn.toLowerCase().includes(q) || c.code.includes(q)).slice(0, 8)
}

export function countryByCode(code: string) {
  return COUNTRIES.find((c) => c.code === code)
}
