export interface Country {
  code: string // ISO 3166-1 alpha-2，小写，直接喂给 Nominatim 的 countrycodes 参数
  nameZh: string
}

// 常见旅行目的地国家/地区，按中文名搜索用。没有做到 ISO 全部 195+ 个是因为
// 家庭旅游APP用不到的冷门地区收益很低，这份列表覆盖亚洲全部+欧美主要国家+
// 大洋洲/中东/非洲热门目的地，足够用；真遇到列表里没有的地方，行程可以不设国家
// （地点搜索就不过滤，退回原来的全球搜索）。
export const COUNTRIES: Country[] = [
  { code: 'cn', nameZh: '中国' },
  { code: 'hk', nameZh: '中国香港' },
  { code: 'mo', nameZh: '中国澳门' },
  { code: 'tw', nameZh: '中国台湾' },
  { code: 'jp', nameZh: '日本' },
  { code: 'kr', nameZh: '韩国' },
  { code: 'kp', nameZh: '朝鲜' },
  { code: 'my', nameZh: '马来西亚' },
  { code: 'sg', nameZh: '新加坡' },
  { code: 'th', nameZh: '泰国' },
  { code: 'vn', nameZh: '越南' },
  { code: 'kh', nameZh: '柬埔寨' },
  { code: 'la', nameZh: '老挝' },
  { code: 'mm', nameZh: '缅甸' },
  { code: 'ph', nameZh: '菲律宾' },
  { code: 'id', nameZh: '印度尼西亚' },
  { code: 'bn', nameZh: '布鲁乃' },
  { code: 'in', nameZh: '印度' },
  { code: 'pk', nameZh: '巴基斯坦' },
  { code: 'bd', nameZh: '孟加拉国' },
  { code: 'lk', nameZh: '斯里兰卡' },
  { code: 'np', nameZh: '尼泊尔' },
  { code: 'bt', nameZh: '不丹' },
  { code: 'mv', nameZh: '马尔代夫' },
  { code: 'mn', nameZh: '蒙古' },
  { code: 'kz', nameZh: '哈萨克斯坦' },
  { code: 'uz', nameZh: '乌兹别克斯坦' },
  { code: 'kg', nameZh: '吉尔吉斯斯坦' },
  { code: 'tj', nameZh: '塔吉克斯坦' },
  { code: 'tm', nameZh: '土库曼斯坦' },
  { code: 'af', nameZh: '阿富汗' },
  { code: 'ae', nameZh: '阿联酋' },
  { code: 'sa', nameZh: '沙特阿拉伯' },
  { code: 'qa', nameZh: '卡塔尔' },
  { code: 'kw', nameZh: '科威特' },
  { code: 'bh', nameZh: '巴林' },
  { code: 'om', nameZh: '阿曼' },
  { code: 'jo', nameZh: '约旦' },
  { code: 'il', nameZh: '以色列' },
  { code: 'ps', nameZh: '巴勒斯坦' },
  { code: 'lb', nameZh: '黎巴嫩' },
  { code: 'tr', nameZh: '土耳其' },
  { code: 'ir', nameZh: '伊朗' },
  { code: 'iq', nameZh: '伊拉克' },
  { code: 'ge', nameZh: '格鲁吉亚' },
  { code: 'am', nameZh: '亚美尼亚' },
  { code: 'az', nameZh: '阿塞拜疆' },
  { code: 'gb', nameZh: '英国' },
  { code: 'ie', nameZh: '爱尔兰' },
  { code: 'fr', nameZh: '法国' },
  { code: 'de', nameZh: '德国' },
  { code: 'nl', nameZh: '荷兰' },
  { code: 'be', nameZh: '比利时' },
  { code: 'lu', nameZh: '卢森堡' },
  { code: 'ch', nameZh: '瑞士' },
  { code: 'at', nameZh: '奥地利' },
  { code: 'it', nameZh: '意大利' },
  { code: 'es', nameZh: '西班牙' },
  { code: 'pt', nameZh: '葡萄牙' },
  { code: 'gr', nameZh: '希腊' },
  { code: 'cy', nameZh: '塞浦路斯' },
  { code: 'mt', nameZh: '马耳他' },
  { code: 'dk', nameZh: '丹麦' },
  { code: 'no', nameZh: '挪威' },
  { code: 'se', nameZh: '瑞典' },
  { code: 'fi', nameZh: '芬兰' },
  { code: 'is', nameZh: '冰岛' },
  { code: 'pl', nameZh: '波兰' },
  { code: 'cz', nameZh: '捷克' },
  { code: 'sk', nameZh: '斯洛伐克' },
  { code: 'hu', nameZh: '匈牙利' },
  { code: 'ro', nameZh: '罗马尼亚' },
  { code: 'bg', nameZh: '保加利亚' },
  { code: 'hr', nameZh: '克罗地亚' },
  { code: 'si', nameZh: '斯洛文尼亚' },
  { code: 'rs', nameZh: '塞尔维亚' },
  { code: 'ba', nameZh: '波黑' },
  { code: 'me', nameZh: '黑山' },
  { code: 'mk', nameZh: '北马其顿' },
  { code: 'al', nameZh: '阿尔巴尼亚' },
  { code: 'ua', nameZh: '乌克兰' },
  { code: 'by', nameZh: '白俄罗斯' },
  { code: 'md', nameZh: '摩尔多瓦' },
  { code: 'ru', nameZh: '俄罗斯' },
  { code: 'ee', nameZh: '爱沙尼亚' },
  { code: 'lv', nameZh: '拉脱维亚' },
  { code: 'lt', nameZh: '立陶宛' },
  { code: 'us', nameZh: '美国' },
  { code: 'ca', nameZh: '加拿大' },
  { code: 'mx', nameZh: '墨西哥' },
  { code: 'cu', nameZh: '古巴' },
  { code: 'jm', nameZh: '牙买加' },
  { code: 'do', nameZh: '多米尼加' },
  { code: 'bs', nameZh: '巴哈马' },
  { code: 'pa', nameZh: '巴拿马' },
  { code: 'cr', nameZh: '哥斯达黎加' },
  { code: 'gt', nameZh: '危地马拉' },
  { code: 'br', nameZh: '巴西' },
  { code: 'ar', nameZh: '阿根廷' },
  { code: 'cl', nameZh: '智利' },
  { code: 'pe', nameZh: '秘鲁' },
  { code: 'co', nameZh: '哥伦比亚' },
  { code: 've', nameZh: '委内瑞拉' },
  { code: 'ec', nameZh: '厄瓜多尔' },
  { code: 'bo', nameZh: '玻利维亚' },
  { code: 'uy', nameZh: '乌拉圭' },
  { code: 'py', nameZh: '巴拉圭' },
  { code: 'au', nameZh: '澳大利亚' },
  { code: 'nz', nameZh: '新西兰' },
  { code: 'fj', nameZh: '斐济' },
  { code: 'pg', nameZh: '巴布亚新几内亚' },
  { code: 'eg', nameZh: '埃及' },
  { code: 'ma', nameZh: '摩洛哥' },
  { code: 'tn', nameZh: '突尼斯' },
  { code: 'za', nameZh: '南非' },
  { code: 'ke', nameZh: '肯尼亚' },
  { code: 'tz', nameZh: '坦桑尼亚' },
  { code: 'et', nameZh: '埃塞俄比亚' },
  { code: 'ng', nameZh: '尼日利亚' },
  { code: 'gh', nameZh: '加纳' },
  { code: 'mu', nameZh: '毛里求斯' },
  { code: 'sc', nameZh: '塞舌尔' },
]

export function searchCountries(query: string): Country[] {
  const q = query.trim().toLowerCase()
  if (!q) return []
  return COUNTRIES.filter((c) => c.nameZh.includes(query.trim()) || c.code.includes(q)).slice(0, 8)
}

export function countryByCode(code: string) {
  return COUNTRIES.find((c) => c.code === code)
}
